version: "3.8"

services:
    web:
      depends_on:
        - backend
      build: ./frontend
      env_file:
        - ./frontend/.env
      ports:
        - 8080:5173
      develop:
        watch:
          - path: ./frontend/package.json
            action: rebuild
          - path: ./frontend/package-lock.json
            action: rebuild
          - path: ./frontend
            target: /watchyourbid
            action: sync

    backend:
      depends_on:
        - database
      build: ./backend
      env_file:
        - ./backend/.env

      environment:
        DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}?schema=public
      ports: 
        - 8000:8000

      develop:
        watch:
          - path: ./backend/package.json
            action: rebuild
          - path: ./backend/package-lock.json
            action: rebuild
          - path: ./backend
            target: /watchyourbid
            action: sync

    database:
      image: postgres:17
      restart: unless-stopped
      env_file:
        - .env
      environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      ports: 
        - 5432:5432
      volumes:
        - watchyourbid:/var/lib/postgresql/data

volumes:
  watchyourbid: